### ISSUE TITLE
Enhancement: Add 'change sticker order'

### ISSUE THREAD

**Issue by JustACuteGirlLookingForAManToFixHerBugs** [zeroone2numeral2/sticker-thief#22]
Hey. Great but. The only thing that I found missing is the ability to change sticker order. 

Meow!

**Comment by zeroone2numeral2** [comment]
Hello @JustACuteGirlLookingForAManToFixHerBugs ,

Sorry for the last answer, for some weird reason GiHub didn't deliver me this notification. 

Unfortunately, the bot API doesn't expose any method to do that easily - but you can do that from [@Stickers](https://t.me/Stickers)! (using the `/ordersticker` command)
