### ISSUE TITLE
[This issue is sponsored by Slack Lives Matter movement] Maybe it's time to remov...

### ISSUE THREAD

**Issue by JustACuteGirlLookingForAManToFixHerBugs** [zeroone2numeral2/sticker-thief#27]
Hey! Maybe it's time to remove the https://t.me/MyPackBot mention? It doesn't work, and it's been down for a loooong time now. 

Btw, cool t-shirt, man.
Take care

**Comment by zeroone2numeral2** [comment]
Yes, makes sense. Will remove the mention from the readme
