### ISSUE TITLE
Error when creating a new pack and adding the first sticker

### ISSUE THREAD

**Issue by byt3h3ad** [zeroone2numeral2/sticker-thief#32]
Shows a `sequence item 0: expected str instance, Sticker found` on sending the first sticker of a new pack
![IMG_20200714_202213](https://user-images.githubusercontent.com/26319721/87440784-fb3b5480-c60f-11ea-9890-01fa33eb582d.jpg)

**Comment by zeroone2numeral2** [comment]
Interesting, thanks for reporting this. I will look into it

**Comment by zeroone2numeral2** [comment]
@byteheadLW you encountered this error while creating an _animated_ pack, right? Can you please tell me the UTC date when you encountered the error? Also, does it always happen? Or have you been able to somehow reproduce it?

**Comment by zeroone2numeral2** [comment]
No worries, I've spotted the error. It's a tricky one. I've made the logs a bit more verbose to catch it in case it happens again
