### ISSUE TITLE
Error while stealing a sticker

### ISSUE THREAD

**Issue by ligix** [zeroone2numeral2/sticker-thief#35]
When sending a .webp file (so a sticker that's not in a sticker set) it doesn't work.

Error message:
`sequence item 0: expected str instance, Sticker found`
Informations given by the bot:
`user_id: 644086084
uuid: 76317ae6-1c5a-48c7-ad1d-44a639ba9ab3
utc: 20200722_212516`

Steps to reproduce:
- send a .webp file

**Comment by zeroone2numeral2** [comment]
Somehow the same issue of #32. Question: you sent a webp file, was it converted to sticker by the client after uploading it? The bot most likely doesn't properly handle pack-less stickers. Interesting
