### ISSUE TITLE
Enhancement - Return stickets stats, as sticker bot

### ISSUE THREAD

**Issue by Tebinski** [zeroone2numeral2/sticker-thief#40]
Or maybe can I add the pack I've made to @Stickers bot and there I will see the stats? BTW Your github repo save my life and endless hours of adding stickers by hand.

**Comment by zeroone2numeral2** [comment]
I'm glad the bot is helpful!

About the stats, by the way, there isn't much I can do - the bot API doesn't allow to get a pack's stats. The only way to do that is using @stickers
