### ISSUE TITLE
Unable to add animated stickers

### ISSUE THREAD

**Issue by shuapok** [zeroone2numeral2/sticker-thief#43]
Hello, stickerthief bot is not able to accept adding animated stickers for some reason. Please help!
![Screenshot_20210306-185654_Telegram](https://user-images.githubusercontent.com/80156573/110205655-4e6e5a00-7eb4-11eb-99bc-bde918a04be2.jpg)

**Comment by zeroone2numeral2** [comment]
Hello there, sorry for the late answer

Can you tell me the pack link? The only thing I can think about is that, for some weird reasons, the bot saved the pack in the database as a static one

**Comment by shuapok** [comment]
Sure! the pack is https://t.me/addstickers/pokkycatreupload_by_stickersthiefbot

**Comment by zeroone2numeral2** [comment]
@shuapok thanks. It looks like the pack is properly flagged as animated in the database too.

I'm afraid you might've ended up in a nested conversation. Can you use `/cancel` _twice_ and post the screenshot?

**Comment by shuapok** [comment]
![Screenshot_20210310-215451_Telegram](https://user-images.githubusercontent.com/80156573/110640005-51868480-81eb-11eb-827e-a27237a6aecc.jpg)
here you go!

**Comment by zeroone2numeral2** [comment]
Wait wait that's the wrong bot

**Comment by shuapok** [comment]
My bad Sir!
![Uploading Screenshot_20210310-220039_Telegram.jpg…]()

**Comment by shuapok** [comment]
My bad Sir!
![Screenshot_20210310-220039_Telegram](https://user-images.githubusercontent.com/80156573/110640772-2f413680-81ec-11eb-9ad3-1fa28687a4b5.jpg)

**Comment by zeroone2numeral2** [comment]
@shuapok thanks. What if you try to add some stickers now?

**Comment by shuapok** [comment]
![Screenshot_20210310-220652_Telegram](https://user-images.githubusercontent.com/80156573/110641406-f0f84700-81ec-11eb-976e-69da77c6bf7e.jpg)
No luck, same issue.

**Comment by zeroone2numeral2** [comment]
Thanks, spotted the bug. If you have two packs with the same title, and the bot asks you to pick the pack by name, it will always expect a static sticker: https://github.com/zeroone2numeral2/sticker-thief/blob/master/bot/handlers/stickers/add.py#L140

Will fix soon. Thanks for spotting the issue

**Comment by shuapok** [comment]
Hahahaa you're the code pro so I'll leave that to you! While I don't understand the codings, I understand what you just described! Thanks for looking into this, and for your amazing bot still :)

**Comment by zeroone2numeral2** [comment]
I updated the bot. Should be fixed now

**Comment by shuapok** [comment]
works like a charm! thanks buddy!
