### ISSUE TITLE
An error occurred while processing the message

### ISSUE THREAD

**Issue by SWGOOSE** [zeroone2numeral2/sticker-thief#50]
An error occurred while processing the message: cannot identify image file <tempfile.SpooledTemporaryFile object at 0x7fcd774bf250>
If you think this is a bug, please report the issue here and include these informations: user_id: 867709148
uuid: 84ffb55f-c323-4db6-8bc2-d82f40dbf32e
utc: 20220509_110241

**Comment by zeroone2numeral2** [comment]
I'm closing this issue because I haven't had time to investigate. If you still have this issue, please open a new ticket
